export class Montos_Consolidados{
    id
    anio 
    mes 
    empresa_id 
    modelo_negocio_id 
    proyecto_id 
    rubro_id 
    enero_abono_financiero 
    enero_cargo_financiero
    enero_abono_resutado
    enero_cargo_resultado 
    febrero_abono_financier
    febrero_abono_resutado 
    febrero_cargo_financier
    febrero_cargo_resultado
    marzo_abono_financiero 
    marzo_abono_resutado 
    marzo_cargo_financiero 
    marzo_cargo_resultado 
    abril_abono_financiero 
    abril_abono_resutado 
    abril_cargo_financiero 
    abril_cargo_resultado 
    mayo_abono_financiero 
    mayo_abono_resutado
    mayo_cargo_financiero 
    mayo_cargo_resultado 
    junio_abono_financiero
    junio_abono_resutado 
    junio_cargo_financiero
    junio_cargo_resultado
    julio_abono_financiero
    julio_abono_resutado 
    julio_cargo_financiero
    julio_cargo_resultado
    agosto_abono_financiero 
    agosto_abono_resutado
    agosto_cargo_financiero
    agosto_cargo_resultado
    septiembre_abono_financiero 
    septiembre_abono_resutado 
    septiembre_cargo_financiero 
    septiembre_cargo_resultado 
    octubre_abono_financiero
    octubre_abono_resutado 
    octubre_cargo_resultado  
    octubre_cargo_financiero 
    noviembre_abono_financiero
    noviembre_abono_resutado 
    noviembre_cargo_financiero
    noviembre_cargo_resultado 
    diciembre_abono_financiero
    diciembre_abono_resutado 
    diciembre_cargo_financiero
    diciembre_cargo_resultado 
    valor_tipo_cambio_financiero
    valor_tipo_cambio_resultado 
    activo: boolean;
    fecha: Date;
}