export interface ProformaDetalle{
        id
        id_proforma
        enero_monto_financiero
        enero_monto_resultado
        febrero_monto_financiero
        febrero_monto_resultado
        marzo_monto_financiero
        marzo_monto_resultado
        abril_monto_financiero
        abril_monto_resultado
        mayo_monto_financiero
        mayo_monto_resultado
        junio_monto_financiero
        junio_monto_resultado
        julio_monto_financiero
        julio_monto_resultado
        agosto_monto_financiero
        agosto_monto_resultado
        septiembre_monto_financiero
        septiembre_monto_resultado
        octubre_monto_financiero
        octubre_monto_resultado
        noviembre_monto_financiero
        noviembre_monto_resultado
        diciembre_monto_financiero
        diciembre_monto_resultado
        acumulado_financiero
        acumulado_resultado
        valor_tipo_cambio_financiero
        valor_tipo_cambio_resultado
        rubro_id
        activo 
        ejercicio_financiero
        ejercicio_resultado
        total_financiero
        total_resultado
        anio 
        modelo_negocio_id
        tipo_captura_id
        periodo_id
        fecha_captura
        nombre_rubro
}