export class RelacionesCat{
    INT_IDRELACION_COMPANIA
    INT_IDCOMPANIA_P
    INT_IDROL_P
    INT_IDMODELO_NEGOCIO_P
    INT_IDPROYECTO_P
    INT_IDCENTROSCOSTO_P
    BOOL_ESTATUS_LOGICO_RELACION_COMPANIA
}